# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tractivity' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tractivity
  pod 'React', :path => '../node_modules/react-native'
  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

  target 'tractivity-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tractivityTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'tractivity-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tractivity-tvOS

  target 'tractivity-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
